
# Dictionnaires de labels partagés
EMOTION_LABELS = {
    'heureux': 'Joie',
    'anxieux': 'Anxiété',
    'triste': 'Tristesse',
    'en_colere': 'Colère',
    'fatigue': 'Fatigue',
    'apeure': 'Peur',
    'surpris': 'Surprise',
    'serein': 'Sérénité'
}

DREAM_TYPE_LABELS = {
    'rêve': 'Rêve',
    'cauchemar': 'Cauchemar'
}

# Message d'erreur centralisé
DREAM_ERROR_MESSAGE = 'Les fils de votre rêve se sont emmêlés... Laissez-moi démêler ce songe et tentez une nouvelle analyse.'

DREAM_SPECIFIC_STOPWORDS = {
    # Mots du rêve
    'rêve',
    'rêver',
    'dormir',
    'nuit',
    'moment',
    'fois',
    'chose',
    'truc',
    'machin',
    'endroit',
    'côté',
    'genre',
    'espèce',
    'sorte',
    'façon',
    'maniÃ¨re',
    'air',
    'impression',
    'sentiment',
    'sensation',
    'souvenir',
    'souviens',
    'rappelle',
    'crois',
    'pense',
    'imagine',
    'semble',
    # Verbes trop génériques
    'faire',
    'avoir',
    'être',
    'aller',
    'dire',
    'voir',
    'savoir',
    'pouvoir',
    'vouloir',
    'devoir',
    'prendre',
    'donner',
    'mettre',
    'partir',
    'venir',
    'arriver',
    'passer',
    'rester',
    'devenir',
    'porter',
    'regarder',
    'entendre',
    'sentir',
    'trouver',
    'laisser',
    'suivre',
    'montrer',
    'demander',
    'parler',
    'tenir',
    'jouer',
    'tourner',
    'ouvrir',
    'fermer',
    'commencer',
    'finir',
    # Mots de liaison et adverbes
    'puis',
    'après',
    'avant',
    'pendant',
    'soudain',
    'tout',
    'très',
    'bien',
    'mal',
    'plus',
    'moins',
    'encore',
    'déjà',
    'toujours',
    'jamais',
    'parfois',
    'souvent',
    'beaucoup',
    'peu',
    'assez',
    'trop',
    'vraiment',
    'plutôt',
    # Mots vagues
    'personne',
    'quelqu',
    'quelque',
    'quelquun',
    'part',
    'endroit',
    'lieu',
    'temps',
    'année',
    'jour',
    'heure',
    'minute',
    'seconde',
    'vie',
    'mort',
    'histoire',
    'situation',
    'problème',
    'question',
    'réponse',
    'idée',
}

SIGNIFICANT_DREAM_VERBS = {
    'voler',
    'tomber',
    'courir',
    'fuir',
    'poursuivre',
    'chaser',
    'nager',
    'escalader',
    'grimper',
    'danser',
    'chanter',
    'crier',
    'pleurer',
    'rire',
    'embrasser',
    'frapper',
    'tuer',
    'mourir',
    'naître',
    'marier',
    'divorcer',
    'conduire',
    'voyager',
    'partir',
    'explorer',
    'chercher',
    'cacher',
}