name: Branch Protection
on:
  pull_request:
    branches: [pre-production, production]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check pre-production source
        if: github.base_ref == 'pre-production'
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "pre-production ne peut recevoir du code que de dev"
            echo "Branche source détectée: ${{ github.head_ref }}"
            echo "Branche source autorisée: dev"
            exit 1
          fi
          echo "Source branch valide pour pre-production (dev → pre-production)"
      
      - name: Check production source  
        if: github.base_ref == 'production'
        run: |
          if [ "${{ github.head_ref }}" != "pre-production" ]; then
            echo "production ne peut recevoir du code que de pre-production"
            echo "Branche source détectée: ${{ github.head_ref }}"
            echo "Branche source autorisée: pre-production"
            exit 1
          fi
          echo "Source branch valide pour production (pre-production → production)"