name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    # Donne à Django ce qu'il veut pendant la CI
    env:
      SECRET_KEY: django-insecure-ci-test-only
      DEBUG: "true"   # évite l'erreur ALLOWED_HOSTS pendant les tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f DreamProject/requirements.txt ]; then pip install -r DreamProject/requirements.txt; fi

      - name: Run Django tests
        run: python DreamProject/manage.py test diary.tests.test_core --verbosity=1 --parallel --keepdb
