name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    # Secrets/vars pour la CI
    env:
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_TEST }}  # ← clé stockée chiffrée
      DEBUG: "false"                                     # on se rapproche de la prod
      ALLOWED_HOSTS: "testserver,localhost,127.0.0.1"    # évite l'erreur côté settings

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f DreamProject/requirements.txt ]; then pip install -r DreamProject/requirements.txt; fi

      - name: Run Django tests
        run: python DreamProject/manage.py test diary.tests.test_core --verbosity=1 --parallel --keepdb
